# Generated by Django 5.0.1 on 2024-01-11 01:53

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sobrenome', models.TextField()),
                ('nascimento', models.DateField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Digite seu número', max_length=31)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
